apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name:  redis-data-redis-master-0-pv 
spec: 
  capacity: 
    storage: 10Gi 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: redis-data-master-0 
  mountOptions: 
    - hard 
    - nfsvers=4.1 
  nfs: 
    path: /mnt/nfs_share/redis/master-0 
    server: 192.168.56.11 
--- 
apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name:  redis-data-redis-replica-0-pv 
spec: 
  capacity: 
    storage: 10Gi 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Recycle 
  storageClassName: redis-data-replica-0 
  mountOptions: 
    - hard 
    - nfsvers=4.1 
  nfs: 
    path: /mnt/nfs_share/redis/replica-0 
    server: 192.168.56.11 
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  finalizers: 
  - kubernetes.io/pvc-protection 
  labels: 
    app.kubernetes.io/component: master 
    app.kubernetes.io/instance: redis 
    app.kubernetes.io/name: redis 
  name: redis-data-redis-master-0 
  namespace: redis 
spec: 
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests: 
      storage: 8Gi 
  volumeMode: Filesystem 
  storageClassName: redis-data-master-0 
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  finalizers: 
  - kubernetes.io/pvc-protection 
  labels: 
    app.kubernetes.io/component: master 
    app.kubernetes.io/instance: redis 
    app.kubernetes.io/name: redis 
  name: redis-data-redis-replicas-0 
  namespace: redis 
spec: 
  accessModes: 
  - ReadWriteOnce 
  resources: 
    requests: 
      storage: 8Gi 
  volumeMode: Filesystem 
  storageClassName: redis-data-replica-0
